<?php
    class Encuesta{
        public $idEvaluador;
        public $tipoSoftware;
        public $rolEvaluador;
        public $Pregunta_1;
        public $Pregunta_2;
        public $Pregunta_3;
        public $Pregunta_4;
        public $Pregunta_5;
        public $Pregunta_6;
        public $Pregunta_7;
        public $Pregunta_8;
        public $Pregunta_9;
        public $Pregunta_10;
        public $Pregunta_11;
        public $Pregunta_12;
        public $Pregunta_13;
        public $Pregunta_14;
        public $Pregunta_15;
        public $Pregunta_16;
        public $Pregunta_17;
        public $Pregunta_18;
        public $Pregunta_19;
        public $Pregunta_20;
        public $Pregunta_21;
        public $Pregunta_22;
        public $Pregunta_23;
        public $Pregunta_24;
        public $Pregunta_25;
        public $Pregunta_26;
        public $Pregunta_27;
        public $Pregunta_28;
        public $Pregunta_29;
        public $Pregunta_30;
        public $Pregunta_31;
        public $Pregunta_32;
        public $Pregunta_33;
        public $Pregunta_34;
        public $Pregunta_35;
        public $Pregunta_36;
        public $Pregunta_37;
        public $Pregunta_38;
        public $Pregunta_39;
        public $Pregunta_40;
        public $Pregunta_41;
        public $Pregunta_42;
        public $Pregunta_43;
        public $Pregunta_44;
        public $Pregunta_45;
        public $Pregunta_46;
        public $Pregunta_47;
        public $Pregunta_48;
        public $Pregunta_49;
        public $Pregunta_50;
        public $Pregunta_51;
        public $Pregunta_52;
        public $Pregunta_53;
        public $Pregunta_54;
        public $Pregunta_55;
        public $Pregunta_56;
        public $Pregunta_57;
        public $Pregunta_58;
        public $Pregunta_59;
        public $Pregunta_60;
        public $Pregunta_61;
        public $Pregunta_62;
        public $Pregunta_63;
        public $comentarios;


        function __construct($id,$t,$r,$p1,$p2,$p3,$p4,$p5,$p6,$p7,$p8,$p9,$p10,$p11,$p12,$p13,$p14,$p15,$p16,$p17,$p18,$p19,$p20,$p21,$p22,$p23,$p24,$p25,$p26,$p27,$p28,$p29,$p30,$p31,$p32,$p33,$p34,$p35,$p36,$p37,$p38,$p39,$p40,$p41,$p42,$p43,$p44,$p45,$p46,$p47,$p48,$p49,$p50,$p51,$p52,$p53,$p54,$p55,$p56,$p57,$p58,$p59,$p60,$p61,$p62,$p63,$c
        ){
            $this->idEvaluador= $id;
            $this->tipoSoftware = $t;
            $this->rolEvaluador = $r;
            $this->Pregunta_1 = $p1;
            $this->Pregunta_2 = $p2;
            $this->Pregunta_3 = $p3;
            $this->Pregunta_4 = $p4;
            $this->Pregunta_5 = $p5;
            $this->Pregunta_6 = $p6;
            $this->Pregunta_7 = $p7;
            $this->Pregunta_8 = $p8;
            $this->Pregunta_9 = $p9;
            $this->Pregunta_10 = $p10;
            $this->Pregunta_11 = $p11;
            $this->Pregunta_12 = $p12;
            $this->Pregunta_13 = $p13;
            $this->Pregunta_14 = $p14;
            $this->Pregunta_15 = $p15;
            $this->Pregunta_16 = $p16;
            $this->Pregunta_17 = $p17;
            $this->Pregunta_18 = $p18;
            $this->Pregunta_19 = $p19;
            $this->Pregunta_20 = $p20;
            $this->Pregunta_21 = $p21;
            $this->Pregunta_22 = $p22;
            $this->Pregunta_23 = $p23;
            $this->Pregunta_24 = $p24;
            $this->Pregunta_25 = $p25;
            $this->Pregunta_26 = $p26;
            $this->Pregunta_27 = $p27;
            $this->Pregunta_28 = $p28;
            $this->Pregunta_29 = $p29;
            $this->Pregunta_30 = $p30;
            $this->Pregunta_31 = $p31;
            $this->Pregunta_32 = $p32;
            $this->Pregunta_33 = $p33;
            $this->Pregunta_34 = $p34;
            $this->Pregunta_35 = $p35;
            $this->Pregunta_36 = $p36;
            $this->Pregunta_37 = $p37;
            $this->Pregunta_38 = $p38;
            $this->Pregunta_39 = $p39;
            $this->Pregunta_40 = $p40;
            $this->Pregunta_41 = $p41;
            $this->Pregunta_42 = $p42;
            $this->Pregunta_43 = $p43;
            $this->Pregunta_44 = $p44;
            $this->Pregunta_45 = $p45;
            $this->Pregunta_46 = $p46;
            $this->Pregunta_47 = $p47;
            $this->Pregunta_48 = $p48;
            $this->Pregunta_49 = $p49;
            $this->Pregunta_50 = $p50;
            $this->Pregunta_51 = $p51;
            $this->Pregunta_52 = $p52;
            $this->Pregunta_53 = $p53;
            $this->Pregunta_54 = $p54;
            $this->Pregunta_55 = $p55;
            $this->Pregunta_56 = $p56;
            $this->Pregunta_57 = $p57;
            $this->Pregunta_58 = $p58;
            $this->Pregunta_59 = $p59;
            $this->Pregunta_60 = $p60;
            $this->Pregunta_61 = $p61;
            $this->Pregunta_62 = $p62;
            $this->Pregunta_63 = $p63;
            $this->comentarios = $c;

        }
    }
?>